import psycopg2
import webscrap as ws

conn = psycopg2.connect( dbname ='movie_data', user = 'postgres', 
                        password = 'root', host = 'localhost', port ='5432')
conn.autocommit = True

cursor = conn.cursor()

#cursor.execute("select version()")

#data = cursor.fetchone()
#print("connection established to:", data)

#sql = '''CREATE database Movie_data'''
#cursor.execute(sql)
#sql = '''SELECT current_database();'''
#cursor.execute(sql)

cursor.execute("DROP TABLE IF EXISTS movie_urls")
sql = '''CREATE TABLE movie_urls
        ( 
            movie_id INT 
                        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            movie_title VARCHAR(255) NOT NULL,
            movie_link  VARCHAR(255) NOT NULL
        )'''

cursor.execute(sql)


for data in range(len(ws.zipped)):
    
    # Create a new record
    sql = "INSERT INTO movie_urls (movie_title, movie_link) VALUES (%s, %s)"
    
    # Execute the query
    cursor.execute(sql, ws.zipped[data])
    
    

cursor.execute("DROP TABLE IF EXISTS url_data")
sql = '''CREATE TABLE url_data
        ( 
            movie_id INT 
                        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            movie_name VARCHAR(255) ,
            release_date VARCHAR(255) ,
            genre VARCHAR(255) ,
            rating INT,
            d_link_1 VARCHAR(255)  
        )'''

cursor.execute(sql)


for data in range(len(ws.zipped2)):
    
    # Create a new record
    sql = "INSERT INTO movie_urls (movie_name, release_date, genre, rating, d_link_1) VALUES (%s, %s, %s, %d, %s)"
    
    # Execute the query
    cursor.execute(sql, ws.zipped2[data])
    
    
# Commit the transaction
conn.commit()
